class MetastoreDataTypes:
    BIGINT = "bigint"
    BOOLEAN = "boolean"
    CHAR = "char"
    DATE = "date"
    DECIMAL = "decimal"
    DOUBLE = "double"
    FLOAT = "float"
    INT = "int"
    SMALLINT = "smallint"
    STRING = "string"
    TIMESTAMP = "timestamp"
    TINYINT = "tinyint"
    VARCHAR = "varchar"
    BINARY = "binary"
